# Beat Analysis
ECG_BEAT_LENGTH = 320
ECG_BEAT_LABELS = ["Normal", "LBBB", "RBBB", "PVC", "APB"]
ECG_BEAT_SYMBOLS = ["N", "L", "R", "V", "A"]
FREQUENCY_SAMPLING = 360
INPUT_FREQUENCY_SAMPLING = 250
DATA_TYPE = "float32"

# Multi-lead Classification
ML_ECG_SIGNAL_LENGTH = 1000
ML_PREQUENCY_SAMPLING = 100
ML_LABELS_LIST = ["NORM", "CD", "HYP", "MI", "STTC"]
